# 配置文件
name: ongwu
description: "适用于 Hexo 的主题，支持 GitHub Pages 托管"
author: "ongwu"
version: "1.3.0"

# 网站信息
site_name: "Ongwu博客 - 个人技术学习"
site_description: "Ongwu博客，分享技术，分享生活，分享一切。"
site_keywords: "技术，生活，分享"

# 导航菜单
menu:
  home: "首页"
  projects: "项目作品"
  tech: "技术深究"
  tutorial: "教程分享"
  ranking: "网站留言"
  other: "其他开发中"

# 链接配置
links:
  other_dev: "https://ongwu.cn"

# 首页配置
index:
  projects_count: 4
  tech_count: 12
  tutorial_count: 12

# 分页配置
pagination:
  per_page: 10

# 页面配置
pages:
  projects:
    title: "项目作品"
    description: "展示我的项目作品和技术实践"
    layout: "projects"
  tech:
    title: "技术深究"
    description: "深入探讨技术原理和实践经验"
    layout: "tech"
  tutorial:
    title: "教程分享"
    description: "分享实用的技术教程和学习心得"
    layout: "tutorial"

# 评论系统
comments: true

# 统计代码
analytics: true

# 本地搜索
local_search:
  enable: true

# 社交链接
social:
  github: ""
  twitter: ""
  email: ""
